### ISSUE TITLE
OSError in 3D

### ISSUE THREAD

**Issue by hpjeonGIT** [stanfordnqp/spins-b#5]
Hi,

I modified wdm2.py as SIM_2D=False, trying to test 3D solver of maxwell-b but it yields an OSerror message. The message is shown below.
Briefly, it looks like maxwell-b makes some scratch file, while python3 from spins-b cannot(?) open it - should read, not create.

Will there be any way to fix this? Or if you have different examples for 3D test, it would be helpful.

Thanks,

Byoungseon

PS. Error message shown below.

[2019-06-18 13:12:37,387][INFO][solver][run_plan] Setting up workspace.
[2019-06-18 13:12:37,389][INFO][solver][run_plan] Running transformation opt_cont0.
/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/scipy/sparse/data.py:71: ComplexWarning: Casting complex values to real discards the imaginary part
  self._deduped_data().astype(dtype, casting=casting, copy=copy),
/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/scipy/sparse/data.py:71: ComplexWarning: Casting complex values to real discards the imaginary part
  self._deduped_data().astype(dtype, casting=casting, copy=copy),
Traceback (most recent call last):
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 119, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 122, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jeonb.py", line 298, in <module>
    main()
  File "jeonb.py", line 61, in main
    problem_graph.run_plan(plan, ".")
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem_graph/solver.py", line 61, in run_plan
    work.run(transformation_param, event_data)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem_graph/workspace.py", line 134, in run
    transform(self.get_object(node.parametrization), event_data)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem_graph/creator_opt.py", line 80, in __call__
    self._start(param)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem_graph/creator_opt.py", line 109, in _start
    monitor_list=self.monitor_lists.start_monitors)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem_graph/workspace.py", line 345, in write
    [self._work.get_object(mon) for mon in monitor_list], param)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem/graph_executor.py", line 87, in eval_fun
    _eval_fun_vals(fun_vals, fun_map, graph, top_sorted_nodes, param)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem/graph_executor.py", line 179, in _eval_fun_vals
    for node_, node_val in zip(heavy_node_block, heavy_node_vals):
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem/graph_executor.py", line 175, in <lambda>
    heavy_node_vals = executor.map(lambda args: _eval_fun(*args),
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem/graph_executor.py", line 122, in _eval_fun
    return fun_map[node].eval(input_vals)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem_graph/creator_em.py", line 230, in eval
    return self._simulate(input_val[0])
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/invdes/problem_graph/creator_em.py", line 293, in _simulate
    bloch_vec=self._bloch_vector,
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/spins/fdfd_solvers/maxwell.py", line 373, in solve
    with h5py.File(file_prefix + 'r') as f:
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 124, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/tmp/jeonb/tmpzlwjit5z/maxwell-20190618-131257-515633c0-91ec-11e9-94cd-70106fbc3864.E_xr', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

**Comment by vcruysse** [comment]
Hi Byoungseon,

This indicates that the simulation did not complete correctly. To understand why, we need to see the log-file of the maxwell solve. You should be able to find this in /tmp/mawell-server-files.

This can happens if there is a hardware issue (typically GPUs) or if the simulation is not correctly defined.

If you can post the end of the maxwell log-file, we should be able to tell more.

Regards,
Dries

**Comment by hpjeonGIT** [comment]
Hi Dries,

Thanks for the reply. 
1) I was using MAXWELL_SERVER_FILES=/tmp/$USER, and this yielded error message shown above. 
2 log files are found at /tmp/$USER, such as:
```
$  more 127.0.0.1:maxwell-20190619-160614-b0cd5b58-92cd-11e9-bd2b-98f2b3e8f1e8.log
  File "/lstr/applications/ava/apps/stanfordnqp/maxwell-b/maxwell-server/maxwell
-solver/fdfd.py", line 23
    def rep(err, info: str = None):
                     ^
SyntaxError: invalid syntax
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus cau
sing
the job to be terminated. The first process to do so was:

  Process name: [[63204,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
simserver.log from `bash start_maxwell` is shown below
```
$ more simserver.log 
[2019-06-19 16:05:42,938][INFO][simserver][main] Solver directory set to /lstr/a
pplications/ava/apps/stanfordnqp/maxwell-b/maxwell-server/maxwell-solver/
[2019-06-19 16:05:42,963][INFO][simserver][main] Number of GPUs detected on syst
em: 4
[2019-06-19 16:05:42,963][INFO][simserver][main] Number of GPUs used per solve: 
1
[2019-06-19 16:05:42,963][INFO][simserver][main] Ready to accept simulations.
[2019-06-19 16:06:16,753][INFO][simserver][main] Solving 127.0.0.1:maxwell-20190
619-160614-b0bbd3a6-92cd-11e9-9b77-98f2b3e8f1e8 as simulation 0
[2019-06-19 16:06:16,805][INFO][simserver][main] Solving 127.0.0.1:maxwell-20190
619-160614-b0cd5b58-92cd-11e9-bd2b-98f2b3e8f1e8 as simulation 1
[2019-06-19 16:06:19,910][INFO][simserver][main] Simulation 0 ended with code 1
[2019-06-19 16:06:20,412][INFO][simserver][main] Simulation 1 ended with code 1
Traceback (most recent call last):
  File "maxwell-server/simserver.py", line 157, in <module>
    main()
  File "maxwell-server/simserver.py", line 99, in main
    time.sleep(1)
KeyboardInterrupt
```

2) when MAXWELL_SERVER_FILES=/tmp/maxwell-server-files, python3 wmd2.py writes scratch files at /tmp/$USER while, maxwell-b server mode makes 2 empty folders at /tmp/maxwell. The problem is that they are not communicating, nothing happens.

Just note that we're using cuda 9.1. Will we need cuda/10 ? 

Any comments are appreciated.

Best regards,

Byoungseon

**Comment by vcruysse** [comment]
Hi Byoungseon,

Thanks for the extra information.

So the second log file shows 'Simulation 0 ended with code 1', meaning that the simulation of  simserver.py did not end successfully, which will result in a invalid h5py file. It should give 'ended with code 0'. 

The first log-file shows the actual error during the solve. It seems to fail on a syntax error very early on. I can recreate the error by running this file with python instead of python3. So I think something went wrong with setting up the environment.

Considering your explanation, I assume that you're not using docker but are doing the manual installation. So to set up the environment you need to do the following (derived from maxwell-b/Dockerfile):
`apt-get update`
`apt-get install -y python3-pip python3-setuptools libhdf5-serial-dev mpich`
`pip3 install virtualenv`
`virtualenv -p python3 pyenv`
`source pyenv/bin/activate`
`pip3 install numpy`
`pip3 install pycuda jinja2 h5py mpi4py`
`pip3 install scipy`
After this you should be running in the a new virtualenv named _pyenv_, which is created in the folder pyenv. (you can exit the )

From now on you should be able to start maxwell by running:
`./start_maxwell`
Please check if everything is correct in this file. 
(PYENV=pyenv if you set the virtualenv up as above, and PYTHON=python3)

Hope this helps,
Dries

**Comment by hpjeonGIT** [comment]
Hi Dries,

1) I tested mpi4py using the example helloworld.py and it works.
2) I tested demo files of pycuda and confirmed that they work.
3) Not sure why, but type hints seems to yield issues. I removed the type hints in fdfd.py and previous error message is gone. Now I see /tmp/$USER has some scratch files of  287MB but no progress.
4) spins.log shows
```
[2019-06-20 10:27:16,870][INFO][solver][run_plan] Setting up workspace.
[2019-06-20 10:27:16,872][INFO][solver][run_plan] Running transformation opt_cont0.
```
We use in-house clusters - this is why we don't use docker - and I will double-check if there is any system-wise limitations. Any comments are appreciated.

Thanks,

BJ

**Comment by vcruysse** [comment]
Hi Byoungseon,

The log looks ok. That is what you should see at the start.
Can you check the maxwell log-files to see if the simulations run successfully?

Just to clarify on the previous post, your issue was that python in the virtualenv that is used to run maxwell is set to python2, while it needs to be python3. This is why you see errors on the type hints. The simserver script will execute "python fdfd.py ..." so if python is not set to python3, your simulation will not work.
If you use `virtualenv -p python3 pyenv`, you should be working in an environment with python3 as default python.

Regards,
Dries

**Comment by hpjeonGIT** [comment]
Hi Dries,

Thanks for the info and reply.
I edited line 146 of maxwell-server/simserver.py 
from:
``` command = ('mpirun -n ' + str(gpus_per_solve) + ' python ' +```
to:
``` command = ('mpirun -n ' + str(gpus_per_solve) + ' -mca pml ob1 python3 ' + ```

Now mwd2.py runs with 3D. I appreciate your help and assistance. 

Best regards,

Byoungseon

PS. `-mca -pm ob1` for ob1 layer in our cuda-aware openmpi.
