### ISSUE TITLE
I get a problem with maxwell-b

### ISSUE THREAD

**Issue by LYX-Rain** [stanfordnqp/spins-b#63]
log files are found at /mnt/maxwell-server-files, such as:

start in main
starting simulate
Traceback (most recent call last):
  File "/app/maxwell-server/maxwell-solver/fdfd.py", line 324, in <module>
    simulate(sys.argv[1])  # Specify name of the job.
  File "/app/maxwell-server/maxwell-solver/fdfd.py", line 34, in simulate
    params = get_parameters(name)
  File "/app/maxwell-server/maxwell-solver/fdfd.py", line 204, in get_parameters
    bloch_phase = f['bloch_phase'].value
AttributeError: 'Dataset' object has no attribute 'value'

**Comment by LYX-Rain** [comment]
I have solve this problem
